// AUTO-GENERATED by scripts/generate-rostr-manifest.mts — do not edit by hand.
// Baked in from ~/workspace/your_files/rostr-core at authoring time so the
// Vercel serverless runtime never reads that directory from disk.
// Generated: 2026-09-17T22:59:58.308Z

export interface RostrAgentDef {
  name: string;
  path: string;
  title: string;
}

export interface RostrSkillDef {
  name: string;
  path: string;
  title: string;
  description: string;
}

export const ROSTR_GENERATED_AT = "2026-09-17T22:59:58.326Z";

export const ROSTR_AGENTS: RostrAgentDef[] = [
  {
    "name": "master",
    "path": "agents/master.md",
    "title": "Master Orchestrator — system instructions"
  },
  {
    "name": "worker",
    "path": "agents/worker.md",
    "title": "Worker — system instructions"
  }
];

export const ROSTR_SKILLS: RostrSkillDef[] = [
  {
    "name": "context-engine",
    "path": "skills/context-engine/SKILL.md",
    "title": "context-engine",
    "description": "The agent's memory. A loop that runs on EVERY session, in the background: it saves the session as a compressed `.md`, stores it, indexes it — and the next session pulls the last one (or all of them) back."
  },
  {
    "name": "create-an-epk",
    "path": "skills/create-an-epk/SKILL.md",
    "title": "create-an-epk",
    "description": "Build a complete electronic press kit for an independent artist: bio, press quotes, music links, photos, tour dates, and contact — assembled into a publishable page."
  }
];
