// AUTO-GENERATED from the legacy vibe-coding-course repo
// Curriculum: 6 modules, 3 labs, 10-day bootcamp
// Regenerate with: python3 scripts/migrate-legacy-content.py
export interface CurriculumSection {
  heading: string
  items: string[]
}

export interface Module {
  num: number
  title: string
  duration: string
  prerequisites: string
  sections: CurriculumSection[]
}

export interface Lab {
  num: number
  title: string
  sections: CurriculumSection[]
}

export interface BootcampDay {
  day: number
  focus: string
  content: string
}

export const curriculumModules: Module[] = [
  {
    "num": 1,
    "title": "What Is AI?",
    "duration": "** 2-3 hours | ",
    "prerequisites": ":",
    "sections": [
      {
        "heading": "Overview",
        "items": [
          "**Duration:** 2-3 hours | **Difficulty:** Beginner | **Prerequisites:** None",
          "**Learning Objectives**",
          "• Distinguish between rule-based systems and machine learning",
          "• Explain how large language models (LLMs) process and generate text",
          "• Understand tokens, context windows, and their practical implications",
          "• Identify the capabilities and limitations of modern generative AI",
          "• Map the current landscape of AI models and their use cases",
          "**Core Content**",
          "**1.1 Machine Learning vs. Rule-Based Systems**",
          "Traditional software follows explicit instructions: if X happens, do Y. Machine learning flips this model — instead of hardcoding rules, we train models on examples and let them infer the rules.",
          "**1.2 How Large Language Models Work**",
          "LLMs are neural networks trained on vast text corpora. They predict the next token (word fragment) given all previous tokens. Key concepts:",
          "• **Training** — The model learns statistical patterns across billions of text examples",
          "• **Inference** — Given a prompt, the model generates tokens one at a time",
          "• **Emergent abilities** — At sufficient scale, models develop capabilities not explicitly trained (translation, reasoning, coding)",
          "**1.3 Tokens and Context Windows**",
          "Tokens are the atomic unit LLMs process. A token is roughly 0.75 words in English.",
          "**Practical implications:**",
          "• Stay within context limits or risk truncation",
          "• Prioritize the most important information first",
          "• Use structured formats (XML, JSON) to maximize useful content per token",
          "**1.4 Generative AI and the Transformer Architecture**",
          "The transformer architecture (Vaswani et al., 2017) underlies all modern LLMs. Its key innovation is the **attention mechanism**, which allows the model to weigh the importance of different parts of the input when generating each output token.",
          "**Why this matters for vibe coding:** Transformers excel at understanding relationships between distant parts of a prompt. This means you can reference earlier instructions, code patterns, or constraints and the model will honor them — if you structure your prompts well.",
          "**1.5 Why AI Is Transforming Software Development**",
          "Three structural shifts:",
          "• **From writing to directing** — Developers describe intent; AI generates implementation",
          "• **From months to minutes** — Prototypes that took weeks now take hours",
          "• **From specialists to generalists** — Non-developers can build working software",
          "**1.6 The Current Model Landscape**",
          "**Key Takeaways**",
          "• AI learns patterns from data rather than following hardcoded rules",
          "• LLMs predict tokens — their power comes from scale and attention",
          "• Context windows are a practical constraint you must design around",
          "• The shift from writing code to directing AI is fundamental",
          "• Different models suit different tasks; choose deliberately",
          "**Practice**",
          "• Count the tokens in a 500-word prompt using an online tokenizer (e.g., OpenAI's tokenizer)",
          "• Compare the output of three different models on the same prompt",
          "• Identify one task you currently do manually that an LLM could assist with",
          "**Further Resources**",
          "• \"Attention Is All You Need\" (Vaswani et al., 2017) — The transformer paper",
          "• resources.json — 27+ external courses from DeepLearning.AI, Coursera, etc.",
          "• tutorials.json — 80+ YouTube tutorials categorized by topic",
          "---"
        ]
      }
    ]
  },
  {
    "num": 2,
    "title": "What Is Vibe Coding?",
    "duration": "** 2 hours | ",
    "prerequisites": ":",
    "sections": [
      {
        "heading": "Overview",
        "items": [
          "**Duration:** 2 hours | **Difficulty:** Beginner | **Prerequisites:** Module 1",
          "**Learning Objectives**",
          "• Define vibe coding and explain its origin",
          "• Master the four-step vibe coding loop",
          "• Distinguish vibe coding from traditional development",
          "• Identify appropriate use cases for vibe coding",
          "• Understand the paradigm shift from programmer to director",
          "**Core Content**",
          "**2.1 Origin Story**",
          "The term \"vibe coding\" emerged from the AI coding community in 2024-2025 to describe a fundamentally new way of building software: describing what you want in natural language and letting AI generate the implementation. It's not about \"vibes\" in the casual sense — it's about maintaining a productive flow state where the AI handles syntax and the human handles intent.",
          "**2.2 The Vibe Coding Loop**",
          "```",
          "Describe ──> Generate ──> Review ──> Refine",
          "↑                                |",
          "└────────────────────────────────┘",
          "```",
          "• **Describe** — Explain what you want in natural language. Be specific about behavior, not implementation.",
          "• **Generate** — The AI produces code. This may take seconds to minutes depending on complexity.",
          "• **Review** — Examine the output. Does it match intent? Are there bugs or edge cases?",
          "• **Refine** — Provide feedback, corrections, or additional context. Loop back to step 1.",
          "**2.3 Traditional Development vs. Vibe Coding**",
          "**2.4 Real-World Use Cases**",
          "• **Prototypes** — MVPs, landing pages, internal tools",
          "• **Full applications** — SaaS products, e-commerce stores, marketplaces",
          "• **Automation scripts** — Data processing, API integrations, web scraping",
          "• **Design-to-code** — Turning mockups into responsive HTML/CSS",
          "• **Legacy modernization** — Translating old codebases to modern frameworks",
          "**2.5 The Paradigm Shift**",
          "Vibe coding represents a shift in software's fundamental bottleneck:",
          "> **Before:** The scarce resource was *coding ability* — who can write the code?",
          ">",
          "> **After:** The scarce resource is *vision* — who knows what to build?",
          "This has profound implications for who builds software, how fast they build it, and what gets built.",
          "**Key Takeaways**",
          "• Vibe coding is Describe → Generate → Review → Refine",
          "• The bottleneck shifts from coding skill to product vision",
          "• Not every task suits vibe coding — choose deliberately",
          "• Review is the most important step in the loop",
          "**Practice**",
          "• Describe a simple app (e.g., a todo list) to a friend without mentioning any code. See if they can understand what you want.",
          "• Use a vibe coding tool (Lovable, Bolt.new, or Claude) to generate a single-page landing page from a text description.",
          "• Identify three projects you've wanted to build but lacked the coding skills for.",
          "**Further Resources**",
          "• Module 3 (The Toolkit) for hands-on tool selection",
          "• tutorials.json — \"Getting Started with Vibe Coding\" video tutorials",
          "---"
        ]
      }
    ]
  },
  {
    "num": 3,
    "title": "The Toolkit",
    "duration": "** 3 hours | ",
    "prerequisites": ":",
    "sections": [
      {
        "heading": "Overview",
        "items": [
          "**Duration:** 3 hours | **Difficulty:** All Levels | **Prerequisites:** Module 2",
          "**Learning Objectives**",
          "• Categorize AI development tools by workflow type",
          "• Compare hosted builders, AI IDEs, and CLI agents",
          "• Select the right tool for any project type",
          "• Build a personal tool stack combining complementary tools",
          "• Understand deployment and backend service options",
          "**Core Content**",
          "**3.1 Tool Categories**",
          "**3.2 Hosted Builders**",
          "**Lovable** — Full-stack app builder with visual editing. Best for: complete applications from a single prompt. Generates React + Supabase apps with authentication and database.",
          "**v0.dev** — Vercel's AI UI generator. Best for: React component generation, landing pages, and UI prototypes. Outputs production-ready Tailwind CSS.",
          "**Bolt.new** — StackBlitz's AI app builder. Best for: full-stack web apps in the browser. Runs code in-browser so you can test immediately.",
          "**Replit** — Online IDE with AI agent. Best for: collaborative development, learning, and quick prototypes. Integrated deployment.",
          "**3.3 AI IDEs**",
          "**Cursor** — VS Code fork with deep AI integration. Features: inline editing, chat, Claude/GPT model choice, codebase-wide understanding. Best for: daily development workflow.",
          "**GitHub Copilot** — Industry-standard AI pair programmer. Features: tab completion, chat, PR reviews. Best for: developers who want AI assistance within their existing editor.",
          "**Windsurf** — AI-native IDE from Codeium. Features: agent mode, multi-file editing, cascade flows. Best for: AI-first development with minimal context switching.",
          "**3.4 CLI Agents**",
          "**Claude Code** — Anthropic's terminal-based AI agent. Best for: complex codebase tasks, refactoring, testing. Works directly in your repository.",
          "**Aider** — Open-source CLI pair programming. Best for: Git-aware AI coding with multi-model support. Tracks which files are changed.",
          "**Codex CLI** — OpenAI's terminal agent. Best for: OpenAI ecosystem development, REPL-style coding.",
          "**3.5 Building Your Stack**",
          "A recommended starter stack:",
          "```",
          "Frontend:      Lovable or v0.dev → Vercel",
          "Backend:       Supabase (Postgres, Auth, Storage)",
          "AI IDE:        Cursor or Claude Code",
          "Prompting:     Claude or GPT-4",
          "Domain:        Namecheap or Cloudflare",
          "```",
          "**3.6 Tool Selection Matrix**",
          "**Key Takeaways**",
          "• Tool selection depends on project type, not personal preference",
          "• Combine tools: hosted builder for frontend, Supabase for backend",
          "• AI IDEs excel at ongoing development; hosted builders excel at greenfield projects",
          "• CLI agents are most powerful for complex, multi-step codebase tasks",
          "**Practice**",
          "• Sign up for 3 tools from different categories (e.g., Lovable, Cursor, Supabase)",
          "• Build the same simple component in two different tools and compare the experience",
          "• Deploy a \"Hello World\" app using Vercel or Netlify",
          "**Further Resources**",
          "• content-hub-data.js — 40+ tools with descriptions and categories",
          "• resources.html — On-site tools directory with reviews",
          "• tutorials.json — Tool-specific setup tutorials",
          "---"
        ]
      }
    ]
  },
  {
    "num": 4,
    "title": "Prompt Chaining",
    "duration": "** 2-3 hours | ",
    "prerequisites": ":",
    "sections": [
      {
        "heading": "Overview",
        "items": [
          "**Duration:** 2-3 hours | **Difficulty:** Intermediate | **Prerequisites:** Module 3",
          "**Learning Objectives**",
          "• Explain why prompt chaining outperforms one-shot prompts for complex tasks",
          "• Structure multi-step AI workflows",
          "• Implement error handling and retry strategies",
          "• Apply real-world chaining patterns",
          "• Chain outputs from one prompt as inputs to the next",
          "**Core Content**",
          "**4.1 Why Chain?**",
          "Single prompts have inherent limitations:",
          "• **Context dilution** — Too many instructions in one prompt reduces adherence",
          "• **Error propagation** — A single error can corrupt the entire output",
          "• **No intermediate validation** — You can't check work mid-generation",
          "• **Token waste** — Unnecessary context carried through every step",
          "Prompt chaining solves these by breaking complex tasks into sequential, verifiable steps.",
          "**4.2 The Chain Pattern**",
          "```",
          "Prompt 1 (Analyze) ──> Output 1 ──> Validate ──> Prompt 2 (Generate) ──> Output 2 ──> ...",
          "↑                                            ↑",
          "Context seed                                  Context seed",
          "```",
          "Each prompt receives:",
          "• The original task context",
          "• The output from the previous step",
          "• A specific instruction for its role in the chain",
          "**4.3 Common Chain Patterns**",
          "**Pattern 1: Plan → Generate → Review**",
          "```",
          "Step 1: \"Analyze this requirements document and create a spec\"",
          "Step 2: \"Using this spec, generate the implementation\"",
          "Step 3: \"Review this implementation against the spec for completeness\"",
          "```",
          "**Pattern 2: Research → Draft → Polish**",
          "```",
          "Step 1: \"Research the topic and provide key facts\"",
          "Step 2: \"Draft a first version using these facts\"",
          "Step 3: \"Polish the draft for tone, clarity, and conciseness\"",
          "```",
          "**Pattern 3: Decompose → Execute → Merge**",
          "```",
          "Step 1: \"Break this feature into independent subtasks\"",
          "Step 2: (Parallel) \"Implement subtask X\" (repeated per subtask)",
          "Step 3: \"Merge all implementations and resolve conflicts\"",
          "```",
          "**4.4 Error Handling**",
          "Each link in the chain should include validation:",
          "• **Format check** — Is the output in the expected structure?",
          "• **Content check** — Does the output contain the required information?",
          "• **Retry logic** — If validation fails, retry with more specific instructions",
          "• **Fallback** — If retries fail, escalate to a different approach or model",
          "**4.5 Context Seeding**",
          "Context seeding is the practice of providing relevant context from previous steps. Best practices:",
          "• Pass only the essential output, not the entire conversation",
          "• Structure passed data as XML or JSON for reliable parsing",
          "• Include metadata: step number, confidence score, relevant files",
          "• Trim irrelevant details before passing to the next step",
          "**Key Takeaways**",
          "• Chaining breaks complex tasks into verifiable steps",
          "• Each step should have a clear input, instruction, and output",
          "• Validation between steps prevents error propagation",
          "• Context seeding enables each step to build on previous work",
          "**Practice**",
          "• Take a complex task (e.g., \"build a blog homepage\") and break it into 3-5 chain steps",
          "• Execute the chain manually by running each prompt separately",
          "• Add validation checks between each step",
          "**Further Resources**",
          "• Module 5 (Context Engineering) — Deeper dive on context management",
          "• Module 6 (Process Engineering) — Scaling chains to production workflows",
          "---"
        ]
      }
    ]
  },
  {
    "num": 5,
    "title": "Context Engineering",
    "duration": "** 3 hours | ",
    "prerequisites": ":",
    "sections": [
      {
        "heading": "Overview",
        "items": [
          "**Duration:** 3 hours | **Difficulty:** Intermediate | **Prerequisites:** Module 4",
          "**Learning Objectives**",
          "• Master the mechanics of context windows and token budgets",
          "• Structure information for maximum AI comprehension",
          "• Prioritize content within limited context",
          "• Engineer reference materials that fit without breaking context",
          "• Iteratively refine context for better results",
          "**Core Content**",
          "**5.1 Context Windows: A Practical Model**",
          "Think of the context window as a limited workspace. Everything in it competes for the model's attention. Understanding this competition is the key to context engineering.",
          "**Context composition:**",
          "```",
          "System Prompt (rules, persona)        ─ 10-20%",
          "Task Instructions (what to do)        ─ 10-20%",
          "Input Data (what to work with)        ─ 40-60%",
          "Reference Material (examples, docs)   ─ 10-30%",
          "Output Format (how to respond)        ─ 5-10%",
          "```",
          "**5.2 What Matters Most**",
          "Models prioritize information based on:",
          "• **Recency** — Information near the beginning and end gets the most attention (the primacy/recency effect)",
          "• **Repetition** — Repeated instructions carry more weight",
          "• **Specificity** — Concrete instructions beat vague guidance",
          "• **Structure** — Well-formatted information is more reliably processed",
          "**5.3 Structuring for Clarity**",
          "**Good:**",
          "```xml",
          "<task>",
          "Build a navigation component with:",
          "• 4 links: Home, About, Services, Contact",
          "• Mobile hamburger menu",
          "• Active state highlighting",
          "• Sticky on scroll",
          "</task>",
          "<constraints>",
          "• Use Tailwind CSS only (no additional libraries)",
          "• Must be responsive (mobile-first)",
          "• Max 50 lines of code",
          "</constraints>",
          "```",
          "**Poor:**",
          "```",
          "I need you to build a navigation. It should have some links and work on mobile too. Probably use Tailwind. Keep it simple. Make it sticky maybe. The links are Home, About, Services, Contact. Actually make sure the active one is highlighted. Oh and hamburger menu on mobile.",
          "```",
          "**5.4 Token Budgeting**",
          "For a 128K token model targeting 25K tokens of context:",
          "```",
          "System prompt:          2K tokens  (8%)",
          "Project context:        3K tokens  (12%)",
          "Codebase references:    5K tokens  (20%)",
          "Current task:           3K tokens  (12%)",
          "Output example:         2K tokens  (8%)",
          "Generated output:       10K tokens (40%)",
          "```",
          "**Rules of thumb:**",
          "• Spend your budget on what the model needs to succeed",
          "• Cut boilerplate and redundant instructions",
          "• Use files/attachments for reference material when available",
          "• Reserve 30-40% of the window for the model's output",
          "**5.5 Iterative Refinement**",
          "Context engineering is not one-shot. The process:",
          "• **Draft** — Write your context based on best guesses",
          "• **Test** — Run the prompt and evaluate the output",
          "• **Audit** — What was missing? What was misinterpreted?",
          "• **Refine** — Adjust structure, content, and prioritization",
          "• **Repeat** — Until consistent quality is achieved",
          "**Key Takeaways**",
          "• Context is a limited resource — budget it deliberately",
          "• Structure, recency, and specificity drive model comprehension",
          "• Allocate 30-40% of context for model output",
          "• Refine iteratively; the first version is never the best",
          "**Practice**",
          "• Take a prompt you've written and calculate its token count",
          "• Rewrite it to use half the tokens while preserving all instructions",
          "• Structure the rewritten version using XML tags",
          "• Test both versions and compare output quality",
          "**Further Resources**",
          "• Module 6 (Process Engineering) — Scaling context practices to teams",
          "• tutorials.json — \"Prompt Engineering Deep Dive\" tutorials",
          "---"
        ]
      }
    ]
  },
  {
    "num": 6,
    "title": "Process Engineering",
    "duration": "** 2-3 hours | ",
    "prerequisites": ":",
    "sections": [
      {
        "heading": "Overview",
        "items": [
          "**Duration:** 2-3 hours | **Difficulty:** Advanced | **Prerequisites:** Module 5",
          "**Learning Objectives**",
          "• Design reproducible AI workflows that consistently produce quality results",
          "• Document processes as standard operating procedures",
          "• Implement quality gates and validation checkpoints",
          "• Scale vibe coding practices from individual to team",
          "• Build automation and tooling around standardized processes",
          "**Core Content**",
          "**6.1 From Prompts to Processes**",
          "Casual vibe coding: open a chat, describe something, get code, move on.",
          "Production vibe coding: define a workflow, document the steps, validate the output, iterate systematically.",
          "The difference is process engineering — treating AI interaction as a designed system rather than a one-off conversation.",
          "**6.2 The Process Blueprint**",
          "Every AI workflow should include:",
          "```",
          "• Input Specification    — What information does this process need?",
          "• Context Assembly       — How do we prepare the context window?",
          "• Step Definitions       — What prompts, in what order, with what validation?",
          "• Quality Gates          — How do we verify output at each step?",
          "• Error Handling         — What happens when a step fails?",
          "• Output Formatting      — How is the final result structured?",
          "• Documentation          — How do others learn and repeat this process?",
          "```",
          "**6.3 Example Process: Feature Generation**",
          "```yaml",
          "process: Generate Frontend Feature",
          "inputs:",
          "• feature_spec: PRD or requirements document",
          "• design_ref: Figma or design mockup",
          "• existing_code: current repo structure",
          "steps:",
          "• id: analyze",
          "prompt: \"Analyze the feature spec and design ref. Identify components, data flow, and edge cases.\"",
          "validate: output contains component list and data flow diagram",
          "• id: plan",
          "prompt: \"Based on the analysis, create an implementation plan with file list and dependencies.\"",
          "validate: output includes file paths and dependency graph",
          "• id: scaffold",
          "prompt: \"Generate the component scaffold with TypeScript types, props interface, and empty handlers.\"",
          "validate: output compiles (TypeScript check)",
          "• id: implement",
          "prompt: \"Using the scaffold, implement the full component with all logic and styling.\"",
          "validate: output passes linting and unit tests",
          "quality_gates:",
          "• All generated files must compile",
          "• No console.log or debug statements",
          "• Follows project's existing patterns",
          "• Handles loading, empty, error states",
          "```",
          "**6.4 Quality Gates**",
          "Quality gates are automated or manual checkpoints that validate output before it moves to the next step:",
          "**6.5 Scaling to Teams**",
          "Key practices for team-wide vibe coding:",
          "• **Shared prompt libraries** — Curated, version-controlled prompt templates",
          "• **Standardized context packs** — Pre-assembled context for common tasks",
          "• **Review protocols** — Clear rules for when AI output needs human review",
          "• **Feedback loops** — Systematic capture of what works and what doesn't",
          "• **Tool standardization** — Agreed-upon tools and configuration",
          "**6.6 Automation Around Processes**",
          "Once a process is documented, it can be automated:",
          "• **Custom CLI tools** — Scripts that assemble context, invoke AI, and run quality gates",
          "• **Git hooks** — Pre-commit validation of AI-generated code",
          "• **CI/CD integration** — Automated process execution in pipelines",
          "• **Prompt management** — Version-controlled prompt repositories",
          "**Key Takeaways**",
          "• Process engineering transforms casual prompting into reproducible workflows",
          "• Every workflow needs: spec, context, steps, gates, error handling, output format, docs",
          "• Quality gates prevent bad output from propagating",
          "• Scaling requires standardization, documentation, and automation",
          "**Practice**",
          "• Document one of your current AI workflows using the process blueprint",
          "• Add a quality gate (e.g., linting check) to your workflow",
          "• Write the process documentation so another person could execute it",
          "• Identify one process you could automate with a custom script",
          "**Further Resources**",
          "• Project Lab 3 (Marketplace) — End-to-end process engineering applied",
          "• content-hub-data.js — Automation and workflow tools",
          "• tutorials.json — Process automation tutorials"
        ]
      }
    ]
  }
]

export const projectLabs: Lab[] = [
  {
    "num": 1,
    "title": "Build a Marketing Website",
    "sections": [
      {
        "heading": "Overview",
        "items": [
          "**Duration:** ~4 hours | **Difficulty:** Beginner | **Cost:** Free",
          "**Overview**",
          "Your first hands-on project. Apply techniques from Modules 1-4 to build a complete, polished marketing website for a fictional (or real) product using any hosted builder (Lovable, v0.dev, or Bolt.new). Deploy to a live URL.",
          "**Prerequisites**",
          "• Module 1: What Is AI (basic AI literacy)",
          "• Module 2: What Is Vibe Coding (the loop)",
          "• Module 3: The Toolkit (tool selection)",
          "• Module 4: Prompt Chaining (basics)",
          "**Learning Objectives**",
          "• Scaffold a multi-page website from a single prompt",
          "• Iterate on design using natural language feedback",
          "• Structure content for marketing conversion",
          "• Deploy to a public URL",
          "• Implement responsive design",
          "**Build Steps**",
          "**Step 1: Define Your Product (30 min)**",
          "Before generating any code, write a one-paragraph product description:",
          "```",
          "Product name, target audience, core value proposition, key features, brand personality.",
          "```",
          "Example:",
          "> \"LaunchKit is a landing page builder for non-technical founders. It offers drag-and-drop templates, one-click deployment, and built-in analytics. The brand is modern, approachable, and confident.\"",
          "**Step 2: Scaffold the Site (45 min)**",
          "Using your chosen tool (recommended: v0.dev for speed or Lovable for full-stack), prompt:",
          "```",
          "Build a marketing website for [product name].",
          "Target audience: [description]",
          "Pages needed: Home, Features, Pricing, About, Contact",
          "Brand personality: [description]",
          "Include: hero section, feature grid, pricing table, testimonial carousel, FAQ accordion, contact form",
          "Style: modern, clean, responsive, [primary color] accent",
          "```",
          "Review the output. Does it match your vision? Note specific things to change.",
          "**Step 3: Refine the Design (45 min)**",
          "Iterate using targeted prompts:",
          "• \"Make the hero section taller with a gradient background\"",
          "• \"Change pricing cards to 3-column layout with featured plan highlighted\"",
          "• \"Add hover animations to all buttons\"",
          "• \"Make the testimonial section use a horizontal scroll on mobile\"",
          "Focus on one change at a time. Review after each.",
          "**Step 4: Add Content (30 min)**",
          "Replace placeholder content with your actual copy:",
          "• Write headlines that convert",
          "• Add real feature descriptions",
          "• Include authentic testimonials",
          "• Add team photos or avatars",
          "**Step 5: Deploy (30 min)**",
          "• Connect your GitHub repository",
          "• Deploy via Vercel or Netlify",
          "• Set up a custom domain (optional)",
          "• Enable HTTPS",
          "**Stretch Goals**",
          "• Add a blog page with at least 2 articles",
          "• Implement dark mode toggle",
          "• Add analytics (Plausible or Umami)",
          "• Create a \"waitlist\" signup form connected to Supabase",
          "• Add page transition animations",
          "**Assessment Criteria**",
          "---"
        ]
      }
    ]
  },
  {
    "num": 2,
    "title": "Build an E-Commerce Store",
    "sections": [
      {
        "heading": "Overview",
        "items": [
          "**Duration:** ~6 hours | **Difficulty:** Intermediate | **Cost:** Free (Stripe test mode)",
          "**Prerequisites**",
          "• Lab 1 completed",
          "• Module 5: Context Engineering",
          "• Basic understanding of databases (Supabase helps)",
          "**Learning Objectives**",
          "• Build a multi-page store with product catalog",
          "• Implement cart and checkout flow",
          "• Integrate payment processing",
          "• Handle user authentication",
          "• Manage product inventory via database",
          "**Build Steps**",
          "**Step 1: Product Catalog (1 hour)**",
          "Prompt the scaffold:",
          "```",
          "Build an e-commerce store for [product category].",
          "Features needed:",
          "• Product listing page with grid view",
          "• Product detail page with images, description, price",
          "• Category filtering",
          "• Search bar",
          "• Sort by price/name/popularity",
          "Use: [tool name], Tailwind CSS, [database if applicable]",
          "```",
          "**Step 2: Shopping Cart (1 hour)**",
          "Add cart functionality:",
          "• Add to cart button",
          "• Cart sidebar or page",
          "• Quantity adjustment",
          "• Remove items",
          "• Price calculation (subtotal, tax, total)",
          "• Cart persistence (local storage or database)",
          "**Step 3: Checkout Flow (1.5 hours)**",
          "• Checkout page with address form",
          "• Order summary",
          "• Payment integration (Stripe test mode)",
          "• Order confirmation page",
          "• Email receipt notification (optional)",
          "**Step 4: Authentication (1 hour)**",
          "• Sign up / log in",
          "• User profile page",
          "• Order history",
          "• Address management",
          "**Step 5: Polish and Deploy (1.5 hours)**",
          "• Loading states for all async operations",
          "• Empty states (empty cart, no orders)",
          "• Error states (payment failed, network error)",
          "• Success states (order confirmed)",
          "• Deploy to production",
          "**Stretch Goals**",
          "• Product reviews and ratings",
          "• Wishlist functionality",
          "• Inventory management dashboard",
          "• Discount codes",
          "• Abandoned cart recovery",
          "• Multi-currency support",
          "**Assessment Criteria**",
          "---"
        ]
      }
    ]
  },
  {
    "num": 3,
    "title": "Build a Directory/Marketplace",
    "sections": [
      {
        "heading": "Overview",
        "items": [
          "**Duration:** ~8 hours | **Difficulty:** Advanced | **Cost:** Free",
          "**Prerequisites**",
          "• Labs 1 and 2 completed",
          "• Module 6: Process Engineering",
          "• Comfortable with databases and authentication",
          "**Learning Objectives**",
          "• Build a multi-tenant platform",
          "• Implement user-generated content",
          "• Design search and filtering systems",
          "• Handle file uploads and media",
          "• Build admin/moderator features",
          "• Apply process engineering to a complex project",
          "**Build Steps**",
          "**Step 1: Define the Platform (30 min)**",
          "Choose your niche:",
          "• **Directory:** Local services, AI tools, courses, events",
          "• **Marketplace:** Digital products, freelance services, rental items",
          "Define: Who lists? Who searches? What's the transaction model?",
          "**Step 2: Database Schema (1 hour)**",
          "Design your schema:",
          "```",
          "users: id, email, name, role (user/admin), avatar",
          "listings: id, title, description, price, category, images[], status, user_id, created_at",
          "categories: id, name, slug, parent_id",
          "reviews: id, rating, text, listing_id, user_id",
          "```",
          "Implement with Supabase or Convex.",
          "**Step 3: Listing Management (1.5 hours)**",
          "• Create listing form with image upload",
          "• Edit/delete listings",
          "• Listing detail page",
          "• User dashboard for managing listings",
          "• Listing status workflow (draft → published → featured)",
          "**Step 4: Search and Discovery (1.5 hours)**",
          "• Full-text search",
          "• Category filtering",
          "• Price range filter",
          "• Location filter (if applicable)",
          "• Sort by relevance, date, price, rating",
          "• Pagination",
          "**Step 5: User Profiles and Reviews (1 hour)**",
          "• Public profile pages",
          "• Review and rating system",
          "• Seller/member reputation",
          "• Contact or inquiry system",
          "**Step 6: Admin Features (1 hour)**",
          "• Admin dashboard",
          "• Listing moderation (approve/reject)",
          "• User management",
          "• Basic analytics",
          "**Step 7: Polish and Deploy (1 hour)**",
          "• Responsive design audit",
          "• Performance optimization",
          "• SEO basics (meta tags, sitemap)",
          "• Accessibility check",
          "• Production deploy",
          "**Stretch Goals**",
          "• Payment processing for marketplace transactions",
          "• Messaging system between users",
          "• Saved searches and alerts",
          "• Featured/boosted listings",
          "• API for third-party access",
          "• i18n support",
          "**Assessment Criteria**"
        ]
      }
    ]
  }
]

export const bootcampDays: BootcampDay[] = [
  {
    "day": 1,
    "focus": "AI Foundations",
    "content": "**Content:** Module 1 (What Is AI)"
  },
  {
    "day": 2,
    "focus": "Vibe Coding Mindset",
    "content": "**Content:** Module 2 (What Is Vibe Coding)"
  },
  {
    "day": 3,
    "focus": "Tool Familiarization",
    "content": "**Content:** Module 3 (The Toolkit)"
  },
  {
    "day": 4,
    "focus": "Prompting Fundamentals",
    "content": "**Content:** Module 4 (Prompt Chaining)"
  },
  {
    "day": 5,
    "focus": "Context Mastery",
    "content": "**Content:** Module 5 (Context Engineering)"
  },
  {
    "day": 6,
    "focus": "Workflow Design",
    "content": "**Content:** Module 6 (Process Engineering)"
  },
  {
    "day": 7,
    "focus": "Build Sprint 1",
    "content": "**Content:** Lab 1 (Marketing Website)"
  },
  {
    "day": 8,
    "focus": "Build Sprint 2",
    "content": "**Content:** Lab 2 (E-Commerce Store, scaffold)"
  },
  {
    "day": 9,
    "focus": "Build Sprint 3",
    "content": "**Content:** Lab 3 (Marketplace, scaffold)"
  },
  {
    "day": 10,
    "focus": "Ship + Portfolio",
    "content": "- Final polish on any project"
  }
]

export const curriculumOverview = "# Vibe Coding Masterclass — Master Curriculum\n\n## Overview\n\nThe Vibe Coding Masterclass is a comprehensive, project-based curriculum designed to take learners from zero coding experience to confidently building production-quality software using AI-powered development tools. The curriculum blends foundational AI literacy, practical tooling, prompt engineering, and hands-on project work.\n\n**Platform:** Vibe Coding Masterclass (vibecodingcourse.z20.web.core.windows.net) + LetsVibeAI (letsvibeai.com)\n\n**Estimated Total Time:** ~20 hours\n\n**Cost:** Free\n\n**Difficulty Progression:** Beginner → Intermediate → Advanced\n\n---\n\n## Curriculum Structure\n\n```\nFoundations (Modules 1-6) ──> Project Labs (1-3) ──> Capstone ──> Portfolio\n       |                          |                       |\n   ~14 hours                  ~18 hours              Self-paced\n   Theory + Practice          Build + Deploy          Independent\n```\n\n---\n\n## Part 1: Foundations — 6 Modules\n\n| Module | Title | Difficulty | Duration | Prerequisites |\n|--------|-------|------------|----------|---------------|\n| 1 | What Is AI? | Beginner | 2-3h | None |\n| 2 | What Is Vibe Coding? | Beginner | 2h | Module 1 |\n| 3 | The Toolkit | All Levels | 3h | Module 2 |\n| 4 | Prompt Chaining | Intermediate | 2-3h | Module 3 |\n| 5 | Context Engineering | Intermediate | 3h | Module 4 |\n| 6 | Process Engineering | Advanced | 2-3h | Module 5 |\n\n---\n\n## Part 2: Project Labs — 3 Builds\n\n| Lab | Project | Difficulty | Duration | Skills Applied |\n|-----|---------|------------|----------|----------------|\n| 1 | Build a Marketing Website | Beginner | ~4h | Modules 1-3, deployment |\n| 2 | Build an E-Commerce Store | Intermediate | ~6h | Modules 1-5, auth, payments |\n| 3 | Build a Directory/Marketplace | Advanced | ~8h | Modules 1-6, full-stack |\n\n---\n\n## Part 3: Supplementary Lessons — Article-Based\n\n8 lessons adapted from the LiveBuildAI content library:\n\n| # | Lesson | Type | Source |\n|---|--------|------|--------|\n| 1 | AI Today: What's Moving | News Briefing | AI Today Sep 2025 |\n| 2 | LiveBuildAI: The Week AI Grew Up | News Briefing | LiveBuildAI 10.6.25 |\n| 3 | LiveBuildAI: September 9, 2025 | News Briefing | LiveBuildAI 9/9/25 |\n| 4 | LiveBuildAI: September 8, 2025 | News Briefing | LiveBuildAI 9/8/25 |\n| 5 | GTM Email Automation with Make.com | How-To Lab | Sales Automation Guide |\n| 6 | LinkedIn Content Automation | How-To Lab | LinkedIn Marketing Automation |\n| 7 | Personalized Email Outreach Engine | How-To Lab "