export interface Tool {
  id: string
  name: string
  description: string
  link: string
  category: string
  useCase?: string
  industry?: string
  featured: boolean
  setting?: string
}

// Complete data from the provided CSV file
export const tools: Tool[] = [
  {
    id: "1",
    name: "Agent Builder Guide",
    description: "Guides beginners in building any AI agent with SDKs, Restack, MCP, and API integration",
    link: "https://chatgpt.com/g/g-6823d7ef9e388191bb15547171896084-agent-builder-guide",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "2",
    name: "Chatbot Architect",
    description: "Builds structured chatbot instructions and guides step-by-step configuration on no-code platforms.",
    link: "https://chatgpt.com/g/g-6820f686c3608191819ebb80e57e990a-chatbot-architect",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "3",
    name: "Poor Richard's GPT",
    description: "Provides quotes and insights from Poor Richard's Almanack",
    link: "https://chatgpt.com/g/g-681ee3be47a0819182590ec346cb304a-poor-richard-s-gpt",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "4",
    name: "Automation Architect",
    description: "Expert in Make, Zapier, n8n; builds custom automations step-by-step",
    link: "https://chatgpt.com/g/g-681e8b22123881919856dcbd09b1765c-automation-architect",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "5",
    name: "Course Builder Assistant",
    description: "Transforms course ideas or documents into structured outlines and full course content.",
    link: "https://chatgpt.com/g/g-68169561b7108191a2eee3758dace731-course-builder-assistant",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "6",
    name: "v0.dev Full Stack App Builder",
    description: "Delivers exactly 10 v0.dev prompts to build full stack app MVPs.",
    link: "https://chatgpt.com/g/g-681685f291a48191a687c6dac28f4412-v0-dev-full-stack-app-builder",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "7",
    name: "Centralized Systems Assistant",
    description: "Assists systems teams with documentation, automation, troubleshooting, and programming tasks.",
    link: "https://chatgpt.com/g/g-68118b25ebd48191be50ecaa749812e5-centralized-systems-assistant",
    category: "Productivity",
    setting: "Private Link",
    featured: false,
  },
  {
    id: "8",
    name: "Custom GPT Builder Guide",
    description: "A calm, expert assistant guiding you step-by-step to design, customize, and refine your perfect GPT.",
    link: "https://chatgpt.com/g/g-681009c908b481919c03570bc6e4c7b2-custom-gpt-builder-guide",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "9",
    name: "Compass GPT Builder",
    description: "Helps users build custom GPTs",
    link: "https://chatgpt.com/g/g-681004f42b9c819199877e2d765d3523-compass-gpt-builder",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "10",
    name: "Custom GPT Guide",
    description: "A step-by-step tutorial guide for building custom GPTs.",
    link: "https://chatgpt.com/g/g-681003e70b4081919f5c7accc1096e21-custom-gpt-guide",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "11",
    name: "Full Stack Copilot",
    description: "Scaffolds components from user prompts using React, Tailwind, shadcn/ui, and full-stack logic.",
    link: "https://chatgpt.com/g/g-681003e70b4081919f5c7accc1096e21-custom-gpt-guide",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "12",
    name: "Jobs to be Done",
    description: "Transforms prompts and docs into AI-ready 'Jobs to Be Done' blueprints with guided flows.",
    link: "https://chatgpt.com/g/g-6802c7da3c688191875f67a5468d82e2-jobs-to-be-done",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "13",
    name: "Prayer Companion",
    description: "Transforms your worries into heartfelt, personalized prayers.",
    link: "https://chatgpt.com/g/g-67f897048ab881919b0d33912bd8481d-prayer-companion",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "14",
    name: "Chatbot Guide Bot (Using Voice Flow)",
    description: "Step-by-step chatbot builder using prompts and downloadable .vf files to help with (voiceflow, etc)",
    link: "https://chatgpt.com/g/g-67f68acfada0819194761d7dc2c8f7bc-chatbot-guide-bot-using-voice-flow",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "15",
    name: "People For GPT",
    description: "Mobilizes action to defend democracy, equity, and justice with People For the American Way.",
    link: "https://chatgpt.com/g/g-67f425684708819190100be5b7052922-people-for-gpt",
    category: "Research & Analysis",
    setting: "Private Link",
    featured: false,
  },
  {
    id: "16",
    name: "Replit Builder",
    description: "Formats and refines prompts for efficient Replit project building",
    link: "https://chatgpt.com/g/g-67ebbfd9befc819187ed1174fd1d8289-replit-builder",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "17",
    name: "PromptBuilder Architect V2",
    description: "Breaks down app ideas into modular prompts for lovable.dev, tailored by plan tier",
    link: "https://chatgpt.com/g/g-67ebbfd7c70c8191b0842c96d89af2ac-promptbuilder-architect-v2",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "18",
    name: "PromptBuilder Architect",
    description: "Creates modular prompt sets for v0.dev, Cursor, and Replit apps with UI, backend, and deploy flows",
    link: "https://chatgpt.com/g/g-67ebb39985c88191bde258e563a05af8-promptbuilder-architect",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "19",
    name: "Unstuck - Newsletter Assistant",
    description: "Creates bold, high-impact newsletters in Aaron Kolosik's voice, using his podcast style.",
    link: "https://chatgpt.com/g/g-67bd5badb390819198e65a35d8affc54-unstuck-newsletter-assistant",
    category: "Productivity",
    setting: "Private Link",
    featured: false,
  },
  {
    id: "20",
    name: "Dropshipping AI Assistant",
    description: "AI-powered tool for automating dropshipping workflows and optimizing product strategy",
    link: "https://chatgpt.com/g/g-67a80e4a464881919f740d5178f2c8dd-dropshipping-ai-assistant",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "21",
    name: "GPT Project Instructions Builder",
    description: "The ultimate builder for elite, deployment-ready GPT Instructions and PRDs",
    link: "https://chatgpt.com/g/g-67a6bd4478e88191ab5fe72a7a0c7375-gpt-project-instructions-builder",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "22",
    name: "Dynamic GPT Project Generator",
    description: "Generates GPT-based projects using PRD and UI inputs.",
    link: "https://chatgpt.com/g/g-67a6627ce5e08191be699f5c2f58eef0-dynamic-gpt-project-generator",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "23",
    name: "Cloud Course Assistant",
    description: "Your personal cloud study assistant",
    link: "https://chatgpt.com/g/g-67a65a6345648191aef0686947a54223-cloud-course-assistant",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "24",
    name: "Project Structure Architect",
    description: "Generates dynamic project structures from PRDs.",
    link: "https://chatgpt.com/g/g-67a5092e227c81919212f7862604d5cf-project-structure-architect",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "25",
    name: "(PRD) Product Requirements Document Builder",
    description: "Generates PRDs, instructions, and custom resources.",
    link: "https://chatgpt.com/g/g-67a465d99950819186563b257bac0d88-prd-product-requirements-document-builder",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "26",
    name: "Tax Assistant Pro GPT",
    description: "Guide users through personal and business tax preparation.",
    link: "https://chatgpt.com/g/g-67a279ecea1481919e8ddc3179102670-tax-assistant-pro-gpt",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "27",
    name: "Call Insights Assistant",
    description: "Analyzes client calls, provides summaries and updates sheets.",
    link: "https://chatgpt.com/g/g-67a27017ace48191aed2c1b72bbf8f9d-call-insights-assistant",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "28",
    name: "Texts Not to Send",
    description: "Send messages to me, not your ex",
    link: "https://chatgpt.com/g/g-67a26b57cb6881918da575f7c7db4129-texts-not-to-send",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "29",
    name: "Dynamic Resource Aggregator",
    description: "Dynamic resource aggregator with user-defined tables.",
    link: "https://chatgpt.com/g/g-67a132ccde2c8191bc1c6f5aaa8a118b-dynamic-resource-aggregator",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "30",
    name: "Job Link Parser & Tracker",
    description: "Parses job links and creates tracking spreadsheets.",
    link: "https://chatgpt.com/g/g-67a119ca27a8819189c4d16e1c18d3cc-job-link-parser-tracker",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "31",
    name: "WealthMind AI",
    description: "A personal budget tracker and financial guide.",
    link: "https://chatgpt.com/g/g-67a0f3c833348191b20061efa83d5847-wealthmind-ai",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "32",
    name: "Job Search Assistant",
    description: "Parse job links, track jobs, and generate tailored resumes",
    link: "https://chatgpt.com/g/g-679fe1e9d5248191849631baced67ec5-job-search-assistant",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "33",
    name: "RAG-DAL Knowledgebase Builder",
    description:
      "Autonomous Knowledge Base (RAG) Builder for Retrieval-Augmented Generation for Dynamic Autonomous Learning",
    link: "https://chatgpt.com/g/g-679e8aa68d70819185c2f072b4bf2065-rag-dal-knowledgebase-builder",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "34",
    name: "Tenny Search",
    description: "Save apartment listing links and parse them into organized CSV format.",
    link: "https://chatgpt.com/g/g-679b58aee3488191baf80c3c9ad90bef-tenny-search",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "35",
    name: "Jesus Guide Me",
    description: "Guides users in Bible and Gnostic study with tailored questions and reflective notes.",
    link: "https://chatgpt.com/g/g-67a0293f54ec8191a8a7925eb7800963-jesus-guide-me",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "36",
    name: "ApplyGPT",
    description: "Guides users in crafting job applications and preparing for interviews.",
    link: "https://chatgpt.com/g/g-679afade60e48191aba8bf66a54d8e8a-applygpt",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "37",
    name: "Assistant Template Generator",
    description: "Generates OpenAI Assistant API templates and setup guides.",
    link: "https://chatgpt.com/g/g-67853e2243348191ab1ad2f89c02d3ef-assistant-template-generator",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "38",
    name: "Personal Video Coach",
    description: "Creates professional video scripts for job pitches or any subject you choose.",
    link: "https://chatgpt.com/g/g-678433cdeaa481918b3e95c5cfccb32d-personal-video-coach",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "39",
    name: "Cosmic Oracle",
    description: "Your cosmic guide for personalized astrology insights.",
    link: "https://chatgpt.com/g/g-6781683b25b88191be28d4d4596c746e-cosmic-oracle",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "40",
    name: "The Profile Wingman",
    description: "Optimize dating profiles with engaging, app-specific content.",
    link: "https://chatgpt.com/g/g-6781573a72dc81919c5d98ef9d0e67bb-the-profile-wingman",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "41",
    name: "Musk Insights Tracker",
    description: "Tracks Elon Musk's social, financial, and political influence.",
    link: "https://chatgpt.com/g/g-678155531ef08191b64844337cdefc05-musk-insights-tracker",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "42",
    name: "Driving Test Genius",
    description: "US Driving Test Prep Assistant for all states.",
    link: "https://chatgpt.com/g/g-677f99e5db28819194f03aed0ae7bd58-driving-test-genius",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "43",
    name: "DOGER",
    description: "Analyzes budgets to find inefficiencies, propose AI solutions, and inspire community contributions.",
    link: "https://chatgpt.com/g/g-677f30c415208191ac4429c9952a492d-doger",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "44",
    name: "AI Palmistry Guide",
    description: "AI-powered virtual palm reader offering insightful, accurate, and personalized palm readings.",
    link: "https://chatgpt.com/g/g-677d762e938481919973a4b587184c40-ai-palmistry-guide",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "45",
    name: "Artist Budget Guide",
    description: "Helps artists create realistic budgets for their projects.",
    link: "https://chatgpt.com/g/g-677c38ca83cc8191962b0d2e84a8f377-artist-budget-guide",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "46",
    name: "Unleash Your Sales Greatness",
    description:
      "Empowers users with practical, empathetic sales training and growth strategies. Powered by unleashyoursalesgreatness.com",
    link: "https://chatgpt.com/g/g-6778556e2ef481918fdead30de50fb95-unleash-your-sales-greatness",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "47",
    name: "SongByrd",
    description: "Your ultimate AI-powered songwriting assistant for hits.",
    link: "https://chatgpt.com/g/g-67723c217e1481918982a34fe2bf360d-songbyrd",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "48",
    name: "Elite Design Studio",
    description: "Agency-level designer with GPT-4o power for elite branding and visual identity systems",
    link: "https://chatgpt.com/g/g-67721e4ac2008191b639f731f8f2b908-elite-design-studio",
    category: "DALL·E",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "49",
    name: "DCASE 312",
    description:
      "Your AI-powered cultural engagement guide for Chicago's Department of Cultural Affairs and Special Events (DCASE).",
    link: "https://chatgpt.com/g/g-676ad343f78c81919598a8969432a163-dcase-312",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "50",
    name: "A&R Campaign Architect",
    description: "Elite A&R strategist for artist campaigns across blogs, playlists, venues, and licensing platforms",
    link: "https://chatgpt.com/g/g-676aa9f4295081918c546999524f2e84-a-r-campaign-architect",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  // Adding more GPTs from the list
  {
    id: "51",
    name: "Instruction Architect",
    description: "Setting the gold standard for AI system instruction design.",
    link: "https://chatgpt.com/g/g-676964c88b088191b70dcd4133ae2595-1-system-instruction-architect",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "52",
    name: "Artispreneur Email Generator",
    description: "Generate emails for your music campaign",
    link: "https://chatgpt.com/g/g-676913cfd1d48191b595497379d27d99-artispreneur-email-generator",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "53",
    name: "PlaceCode",
    description:
      "Designs and optimizes web solutions with tailored scripts, seamless integrations, and deployment-ready assets.",
    link: "https://chatgpt.com/g/g-67689e24ba088191915d9f046ca55c6d-placecode",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "54",
    name: "Horizon UI Copilot",
    description: "Build and deploy sleek UIs for assistants using Horizon UI.",
    link: "https://chatgpt.com/g/g-6765c87b5548819197f8a8b5191d253c-horizon-ui-copilot",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "55",
    name: "Custom UI Chatbot Assistant",
    description: "Configures CSS/HTML Templates and project files to match open ai assistant apis",
    link: "https://chatgpt.com/g/g-67612822fb34819198549b0396a5d6e5-custom-ui-chatbot-assistant",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "56",
    name: "Omni Architect",
    description: "Master problem solver and workflow designer across all domains.",
    link: "https://chatgpt.com/g/g-6749234181b88191a9e9cf4940f29900-omni-architect",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "57",
    name: "Sixth Automation",
    description: "Expert automation assistant for Make.com and Softr scenarios.",
    link: "https://chatgpt.com/g/g-673eed917eec81918514e2a40f890fd6-sixth-automation",
    category: "Productivity",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "58",
    name: "Artist Business Plan Generator",
    description: "Guides artists in building tailored business plans and growth strategies.",
    link: "https://chatgpt.com/g/g-673240bec7c08190af4bf954dcef16a5-artist-business-plan-generator",
    category: "Business",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "59",
    name: "HouseofAshburn Executive Assistant",
    description: "Luxury brand executive assistant driving strategic growth",
    link: "https://chatgpt.com/g/g-WtZYSpBvN-houseofashburn-executive-assistant",
    category: "Business",
    setting: "Private Link",
    featured: false,
  },
  {
    id: "60",
    name: "My Smart Tax Advisor",
    description: "Personalized U.S. tax assistant for entrepreneurs",
    link: "https://chatgpt.com/g/g-MQEBlp8iN-my-smart-tax-advisor",
    category: "Finance",
    setting: "GPT Store",
    featured: false,
  },
  // Adding more entries to reach at least 100 GPTs
  {
    id: "61",
    name: "Image Sourcing Analyst",
    description: "Extracts relevant image URLs from sites for visual content enhancement",
    link: "https://chatgpt.com/g/g-bVKch7kAf-image-sourcing-analyst",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "62",
    name: "RSS Assist",
    description: "Transforms RSS feeds into engaging, SEO-optimized blogs with ethical attribution and rich insights.",
    link: "https://chatgpt.com/g/g-gOBjQdiWm-rss-assist",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "63",
    name: "NPAO Bot",
    description: "Helps users prioritize and analyze tasks using N.P.A.O. for clarity and growth.",
    link: "https://chatgpt.com/g/g-5BWmDw3PN-npao-bot",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "64",
    name: "The Tie Breaker",
    description: "Builds a futuristic voting platform driven by AI and blockchain for smart governance.",
    link: "https://chatgpt.com/g/g-N1teuetQp-the-tie-breaker",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "65",
    name: "Ultimate Survival AI",
    description: "Your definitive companion for mastering survival in any environment.",
    link: "https://chatgpt.com/g/g-NujG6TmqR-ultimate-survival-ai",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "66",
    name: "Visual Content Studio",
    description: "Convert text into visual formats, automate creative workflows, and generate product videos.",
    link: "https://chatgpt.com/g/g-VEJl08aRo-visual-content-studio",
    category: "DALL-E",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "67",
    name: "Sales Process Assistant",
    description: "AI assistant for seamless sales automation, CRM integration, and actionable sales insights.",
    link: "https://chatgpt.com/g/g-HqlEVB4Se-sales-process-assistant",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "68",
    name: "Business Automation Guide",
    description: "Expert guide for automating business workflows and integrating tools like Softr, Zapier, and GPT.",
    link: "https://chatgpt.com/g/g-f4GHCIImp-business-automation-guide",
    category: "Business",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "69",
    name: "Technical Writing Pro",
    description: "Expert in refining technical copy, creating processes, and crafting goal-oriented documents.",
    link: "https://chatgpt.com/g/g-DfNpo3dNS-technical-writing-pro",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "70",
    name: "Crime Tracker Chicago",
    description: "Real-time crime intelligence for Chicago with maps, reports, and predictive analytics.",
    link: "https://chatgpt.com/g/g-pKjwPnJ18-crime-tracker-chicago",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "71",
    name: "Outreach Automator",
    description: "Automates email outreach tasks in HubSpot with personalized emails.",
    link: "https://chatgpt.com/g/g-lISjbhdPs-outreach-automator",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "72",
    name: "Strategic Business Architect",
    description: "Expert guide for strategic growth, sales optimization, and business model innovation.",
    link: "https://chatgpt.com/g/g-sVjPH8xUg-strategic-business-architect",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "73",
    name: "AutomateGPT",
    description: "Automate custom GPT creation based on Airtable data.",
    link: "https://chatgpt.com/g/g-p7fv7jXmo-automategpt",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "74",
    name: "Unstuck Master Plan GPT",
    description: "Conversational AI coach guiding users step-by-step through the Power Assessment.",
    link: "https://chatgpt.com/g/g-73w9nmSXx-unstuck-master-plan-gpt",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "75",
    name: "Business Audit",
    description: "Dynamic business audit and strategic planning assistant.",
    link: "https://chatgpt.com/g/g-ATFdQizuP-business-audit",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "76",
    name: "GPT Configurator",
    description: "Creates detailed, formatted documents from GPT configurations.",
    link: "https://chatgpt.com/g/g-rIfzVdt47-gpt-configurator",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "77",
    name: "BLK Heights Career Coach",
    description:
      "Empowering coach and content guide for BLK Heights' tech-driven community. Powered by www.blkheights.com.",
    link: "https://chatgpt.com/g/g-faUugyEGJ-blk-heights-career-coach",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "78",
    name: "List Manager",
    description: "Organizes and manages apartment listings with categorization and search tools.",
    link: "https://chatgpt.com/g/g-ZJWsFRQRZ-list-manager",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "79",
    name: "HUMINT",
    description: "Simulates and teaches human intelligence skills focused on self-awareness and empathy.",
    link: "https://chatgpt.com/g/g-vZ4ywRsqf-humint",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "80",
    name: "Image Scraper Pro",
    description: "Efficient GPT for scraping and returning relevant image URLs.",
    link: "https://chatgpt.com/g/g-FuPsdlwkZ-image-scraper-pro",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  // Adding more entries to complete the list
  {
    id: "81",
    name: "Web Image Extractor",
    description: "Extracts and returns the most relevant image URLs from websites.",
    link: "https://chatgpt.com/g/g-SrwBDwnJd-web-image-extractor",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "82",
    name: "Political Campaign Guide",
    description:
      "Your comprehensive guide for political campaigns and elections, providing direct answers and insights.",
    link: "https://chatgpt.com/g/g-tL61iT0zl-political-campaign-guide",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "83",
    name: "Prossley",
    description:
      "AI-powered sales architect delivering actionable, data-driven insights for optimized client engagement.",
    link: "https://chatgpt.com/g/g-s0HyR5nM8-prossley",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "84",
    name: "Revenue Strategist",
    description: "Guides businesses in crafting custom sales strategies using Predictable Revenue Modeling.",
    link: "https://chatgpt.com/g/g-IkaglNabJ-revenue-strategist",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "85",
    name: "ArtBeat Covers",
    description: "Helps artists create visually stunning cover art tailored to their music.",
    link: "https://chatgpt.com/g/g-Ja6aQCuTg-artbeat-covers",
    category: "DALL-E",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "86",
    name: "Music Biz Daily Digest",
    description: "Creates a daily digest of top music industry business news.",
    link: "https://chatgpt.com/g/g-tkvx0g5zl-music-biz-daily-digest",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "87",
    name: "Artist Resource Hub",
    description: "Your ultimate guide to music industry resources, deals, and news.",
    link: "https://chatgpt.com/g/g-gmfOMW8bv-artist-resource-hub",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "88",
    name: "Hero Image Extractor Pro",
    description: "Effortlessly extracts hero images from websites for seamless data integration.",
    link: "https://chatgpt.com/g/g-kyazQOR1h-hero-image-extractor-pro",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "89",
    name: "Mighty Oaks Capital Assistant",
    description: "AI chatbot for MightyOaksCapitalPartners.com, streamlining user inquiries and engagement.",
    link: "https://chatgpt.com/g/g-pB6vFykTE-mighty-oaks-capital-assistant",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "90",
    name: "GPT Creator Pro",
    description: "Advanced GPT architect specializing in prompt engineering, optimization, and deployment.",
    link: "https://chatgpt.com/g/g-s9YtL560v-gpt-creator-pro",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "91",
    name: "DocuScript",
    description: "Guide users in creating compelling documentaries from start to finish.",
    link: "https://chatgpt.com/g/g-fohlSe9g9-docuscript",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "92",
    name: "AI Newsletter Assistant",
    description: "Builds and writes daily AI newsletters with fresh news and smart resource curation.",
    link: "https://chatgpt.com/g/g-68120a8c7aa08191bd2da528ea3bd7ee-ai-newsletter-assistant",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "93",
    name: "Artist Interview Bot",
    description: "Collects and shares artists' insights for aspiring talents.",
    link: "https://chatgpt.com/g/g-mMIuI7n2u-artist-interview-bot",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "94",
    name: "EPK Builder",
    description: "Creates EPKs for musicians, crafting engaging bios and media kits.",
    link: "https://chatgpt.com/g/g-k1G0USEyh-epk-builder",
    category: "Writing",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "95",
    name: "Artist AI Coach",
    description: "Connects artists with AI-powered personal tutors based on real artist experiences.",
    link: "https://chatgpt.com/g/g-y8hqJDMiF-artist-ai-coach",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "96",
    name: "ArtistConnect",
    description: "Connect with artists for real advice, mentorship, and coaching based on true journeys.",
    link: "https://chatgpt.com/g/g-EWhVQersh-artistconnect",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "97",
    name: "ChicagoESQ",
    description: "Learn about Chicago Justice System",
    link: "https://chatgpt.com/g/g-N0Vkz5UV0-chicagoesq",
    category: "Education",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "98",
    name: "ERC Assistant",
    description: "Guides in filling out employee retention credit forms",
    link: "https://chatgpt.com/g/g-bq6pdBN1d-erc-assistant",
    category: "Finance",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "99",
    name: "AlgoVest",
    description: "Personal Investment Algorithm Creator",
    link: "https://chatgpt.com/g/g-ZKskCRKA7-algovest",
    category: "Finance",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "100",
    name: "RSS Aggregator",
    description: "Curates and exports tailored RSS feed lists for any industry or niche.",
    link: "https://chatgpt.com/g/g-jKy7Famu9-rss-aggregator",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "101",
    name: "Side Hustle Finder",
    description: "Helps users discover quick and easy side hustle opportunities via mobile apps and platforms.",
    link: "https://chatgpt.com/g/g-PVbv64iXx-side-hustle-finder",
    category: "Business",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "102",
    name: "FlowBud",
    description: "Build custom agents with OpenAI, Zapier, Make, Dialogflow, and more.",
    link: "https://chatgpt.com/g/g-BlpSmLwM3-flowbud",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "103",
    name: "Highly Suggested Prompts (HSPs)",
    description: "Refines prompts with precision for optimal AI performance and clarity.",
    link: "https://chatgpt.com/g/g-haeo2jTUS-highly-suggested-prompts-hsps",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "104",
    name: "Relevance AI Custom Agent Builder",
    description:
      "Uses Relevance.ai documentation to help guide you with agent, tool and bot creation. Just enter a prompt of what you'd like to build!",
    link: "https://chatgpt.com/g/g-pSPhvxvMh-relevance-ai-custom-agent-builder",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "105",
    name: "Relevance AI Assistant",
    description:
      "Uses Relevance.ai documentation to help guide you with agent, tool and bot creation. Just enter a prompt of what you'd like to build!",
    link: "https://chatgpt.com/g/g-bymrCVdYD-relevance-ai-assistant",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "106",
    name: "Jo Kraft",
    description: "Expert joke crafter who helps develop jokes based on user's style.",
    link: "https://chatgpt.com/g/g-pCiEuWm6P-jo-kraft",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "107",
    name: "Showcase",
    description: "Create your open mic, showcase, or release party.",
    link: "https://chatgpt.com/g/g-Fzqo1n15t-showcase",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "108",
    name: "Artist Bio Creator",
    description: "Guides musicians through creating professional artist biographies.",
    link: "https://chatgpt.com/g/g-aWdPi7rXs-artist-bio-creator",
    category: "Writing",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "109",
    name: "Stori",
    description:
      "I'll guide you through writing professional scripts and storyboards, complete with visual storytelling tools.",
    link: "https://chatgpt.com/g/g-e1Hu90qGa-stori",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "110",
    name: "Uney: Illinois Unemployment Guide",
    description: "Expert on Illinois unemployment insurance.",
    link: "https://chatgpt.com/g/g-cUZm3JhdJ-uney-illinois-unemployment-guide",
    category: "Finance",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "111",
    name: "Recalla",
    description: "Intuitive recall agent providing detailed recall lists.",
    link: "https://chatgpt.com/g/g-Y4fMRqFFf-recalla",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "112",
    name: "Code Camp Mentor",
    description: "Your personalized coding bootcamp tutor for Python and AI.",
    link: "https://chatgpt.com/g/g-b1hlsjRXX-code-camp-mentor",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "113",
    name: "Sales Commander",
    description: "General of Your Sales Army",
    link: "https://chatgpt.com/g/g-MqLy87WdT-sales-commander",
    category: "Business",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "114",
    name: "Armie",
    description: "Advanced artist development and management bot assisting artists to become entrepreneurs.",
    link: "https://chatgpt.com/g/g-YwyaCFT7Y-armie",
    category: "Business",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "115",
    name: "AuctoPilot",
    description: "Find auctions, foreclosures, estate sales near you.",
    link: "https://chatgpt.com/g/g-98xUvWZ0A-auctopilot",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "116",
    name: "Theory Formulation Assistant",
    description:
      "Assists in theory formulation and investigation, explaining and applying the 'nx' theory, where x represents known possibilities and n represents unknown possibilities.",
    link: "https://chatgpt.com/g/g-sxSTVv4og-theory-formulation-assistant",
    category: "Research & Analysis",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "117",
    name: "InterviewGPT",
    description: "Streamlined job application assistant for optimizing resumes and managing application tracking.",
    link: "https://chatgpt.com/g/g-IcSrCDQKp-interviewgpt",
    category: "Productivity",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "118",
    name: "Algorithm Architect",
    description: "Helps create algorithms and code with tutorials.",
    link: "https://chatgpt.com/g/g-U2en92Qdn-algorithm-architect",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "119",
    name: "WordUp",
    description: "Wordpress Assistant",
    link: "https://chatgpt.com/g/g-L6f108GSb-wordup",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "120",
    name: "API Guide",
    description:
      "Allow me to make custom actions and functions using APIs, by uploading documentation and asking for step-by-step instructions.",
    link: "https://chatgpt.com/g/g-vSbY2y8pd-api-guide",
    category: "Programming",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "121",
    name: "SyncMaster",
    description: "Find music supervisors and libraries to submit your music to.",
    link: "https://chatgpt.com/g/g-hvolaQ0yh-syncmaster",
    category: "Music",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "122",
    name: "SongVid",
    description: "Powered by Artispreneur. Create a music video with stock footage based on a song upload",
    link: "https://chatgpt.com/g/g-z0ounFAlV-songvid",
    category: "DALL-E",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "123",
    name: "Reggie: P.R.O.",
    description: "A specialized assistant helping users register for PROs and manage music portfolios.",
    link: "https://chatgpt.com/g/g-2eyNECKRg-reggie-p-r-o",
    category: "Music",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "124",
    name: "MicSpot",
    description:
      "Powered by Artispreneur. This GPT finds open mics in your area for Comedy and Music. All content generated from www.badslava.com",
    link: "https://chatgpt.com/g/g-maDxBXHrX-micspot",
    category: "Lifestyle",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "125",
    name: "E-Milly",
    description: "Crafts data-driven campaigns for music promotion.",
    link: "https://chatgpt.com/g/g-gmDJhtOzO-e-milly",
    category: "Marketing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "126",
    name: "Product Description Editor",
    description: "Creates polished product descriptions for ecommerce platforms like WooCommerce.",
    link: "https://chatgpt.com/g/g-kHM2PFMAp-product-description-editor",
    category: "Writing",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "127",
    name: "MusicTracts - Split Sheet Agreement",
    description: "Your go-to tool for generating professional Music Split Sheet Agreements effortlessly.",
    link: "https://chatgpt.com/g/g-xtRcRaLBy-musictracts-split-sheet-agreement",
    category: "Legal",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "128",
    name: "Music Contract Assistant",
    description:
      "Powered by Artispreneur.com. Enter a prompt for a music contract, upload your own for review, or submit your information to fill in a template.",
    link: "https://chatgpt.com/g/g-8a5gA1RQf-music-contract-assistant",
    category: "Legal",
    setting: "GPT Store",
    featured: true,
  },
  {
    id: "129",
    name: "Textvi",
    description: "Upload text and create video",
    link: "https://chatgpt.com/g/g-FULmAXEmh-textvi",
    category: "DALL-E",
    setting: "GPT Store",
    featured: false,
  },
  {
    id: "130",
    name: "API Integration Architect Pro",
    description: "Expert in API schema creation, validation, and seamless AI integrations.",
    link: "https://chatgpt.com/g/g-9KZmYIrNN-api-integration-architect-pro",
    category: "Programming",
    setting: "GPT Store",
    featured: false,
  },
]

export const getToolById = (id: string): Tool | undefined => {
  return tools.find((tool) => tool.id === id)
}

export const getToolsByCategory = (category: string): Tool[] => {
  return tools.filter((tool) => tool.category === category)
}

export const getFeaturedTools = (): Tool[] => {
  return tools.filter((tool) => tool.featured)
}

export const getAllCategories = (): string[] => {
  const categories = new Set<string>()
  tools.forEach((tool) => {
    if (tool.category) {
      categories.add(tool.category)
    }
  })
  return Array.from(categories)
}

export const getAllUseCases = (): string[] => {
  const useCases = new Set<string>()
  tools.forEach((tool) => {
    if (tool.useCase) {
      useCases.add(tool.useCase)
    }
  })
  return Array.from(useCases)
}

export const getAllIndustries = (): string[] => {
  const industries = new Set<string>()
  tools.forEach((tool) => {
    if (tool.industry) {
      industries.add(tool.industry)
    }
  })
  return Array.from(industries)
}
