// Generates lib/rostr/manifest.ts from the rostr-core definitions at
// ~/workspace/your_files/rostr-core (agents/*.md + skills/*/SKILL.md).
//
// The manifest is BAKED IN at authoring/build time: the Next.js app never
// reads the rostr-core directory from the serverless filesystem at runtime
// (it doesn't exist on Vercel). Re-run this script whenever agents or skills
// change, then commit the regenerated manifest.ts.
//
//   npx tsx scripts/generate-rostr-manifest.mts
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const ROSTR_CORE = join(
  process.env.HOME ?? "",
  "workspace/your_files/rostr-core"
);

function firstHeading(content: string): string {
  const line = content
    .split("\n")
    .find((l) => l.trim().startsWith("#")) ?? "";
  return line.replace(/^#+\s*/, "").replace(/^Skill:\s*/i, "").trim();
}

function clean(text: string): string {
  return text
    .replace(/^>\s?/gm, "")
    .replace(/\*\*/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

// First non-empty paragraph after the title-ish lines, for list display.
// Prefers the body under a "## Description" heading when present.
function firstParagraph(content: string): string {
  const lines = content.split("\n");
  const descIdx = lines.findIndex((l) => /^##\s+description\b/i.test(l.trim()));
  const scope = descIdx >= 0 ? lines.slice(descIdx + 1) : lines;
  const paras: string[] = [];
  let current: string[] = [];
  for (const line of scope) {
    const trimmed = line.trim();
    if (trimmed === "" || /^#{1,6}\s/.test(trimmed)) {
      if (current.length > 0) {
        paras.push(current.join(" ").trim());
        current = [];
      }
      if (descIdx >= 0 && /^#{1,6}\s/.test(trimmed)) break; // next section
    } else {
      current.push(trimmed.replace(/^>\s?/, ""));
    }
  }
  if (current.length > 0) paras.push(current.join(" ").trim());
  const body = paras.find((p) => !p.startsWith("**") && p.length > 20);
  return clean(body ?? "").slice(0, 280);
}

interface AgentDef {
  name: string;
  path: string;
  title: string;
}
interface SkillDef {
  name: string;
  path: string;
  title: string;
  description: string;
}

const agents: AgentDef[] = [];
for (const file of readdirSync(join(ROSTR_CORE, "agents"))) {
  if (!file.endsWith(".md")) continue;
  const content = readFileSync(join(ROSTR_CORE, "agents", file), "utf8");
  agents.push({
    name: file.replace(/\.md$/, ""),
    path: `agents/${file}`,
    title: firstHeading(content),
  });
}

const skills: SkillDef[] = [];
for (const dir of readdirSync(join(ROSTR_CORE, "skills"))) {
  const skillFile = join(ROSTR_CORE, "skills", dir, "SKILL.md");
  let content: string;
  try {
    content = readFileSync(skillFile, "utf8");
  } catch {
    continue;
  }
  skills.push({
    name: dir,
    path: `skills/${dir}/SKILL.md`,
    title: firstHeading(content),
    description: firstParagraph(content),
  });
}

const out = `// AUTO-GENERATED by scripts/generate-rostr-manifest.mts — do not edit by hand.
// Baked in from ~/workspace/your_files/rostr-core at authoring time so the
// Vercel serverless runtime never reads that directory from disk.
// Generated: ${new Date().toISOString()}

export interface RostrAgentDef {
  name: string;
  path: string;
  title: string;
}

export interface RostrSkillDef {
  name: string;
  path: string;
  title: string;
  description: string;
}

export const ROSTR_GENERATED_AT = "${new Date().toISOString()}";

export const ROSTR_AGENTS: RostrAgentDef[] = ${JSON.stringify(
  agents,
  null,
  2
)};

export const ROSTR_SKILLS: RostrSkillDef[] = ${JSON.stringify(
  skills,
  null,
  2
)};
`;

mkdirSync(join(process.cwd(), "lib/rostr"), { recursive: true });
writeFileSync(join(process.cwd(), "lib/rostr/manifest.ts"), out, "utf8");
console.log(
  `Wrote lib/rostr/manifest.ts: ${agents.length} agents, ${skills.length} skills`
);
